var searchData=
[
  ['samesize_2ephp_7234',['SameSize.php',['../_same_size_8php.html',1,'']]],
  ['scalar_2ephp_7235',['Scalar.php',['../nikic_2php-parser_2lib_2_php_parser_2_node_2_scalar_8php.html',1,'(Global Namespace)'],['../phpdocumentor_2type-resolver_2src_2_types_2_scalar_8php.html',1,'(Global Namespace)']]],
  ['scalarcomparator_2ephp_7236',['ScalarComparator.php',['../_scalar_comparator_8php.html',1,'']]],
  ['schemadetectionresult_2ephp_7237',['SchemaDetectionResult.php',['../_schema_detection_result_8php.html',1,'']]],
  ['schemadetector_2ephp_7238',['SchemaDetector.php',['../_schema_detector_8php.html',1,'']]],
  ['schemafinder_2ephp_7239',['SchemaFinder.php',['../_schema_finder_8php.html',1,'']]],
  ['screen_2dreaders_2emd_7240',['screen-readers.md',['../screen-readers_8md.html',1,'']]],
  ['scrollspy_2emd_7241',['scrollspy.md',['../scrollspy_8md.html',1,'']]],
  ['sectioniteratorobjects_2ephp_7242',['SectionIteratorObjects.php',['../_section_iterator_objects_8php.html',1,'']]],
  ['sectionmagicobjects_2ephp_7243',['SectionMagicObjects.php',['../_section_magic_objects_8php.html',1,'']]],
  ['sectionobjects_2ephp_7244',['SectionObjects.php',['../_section_objects_8php.html',1,'']]],
  ['sections_2ephp_7245',['Sections.php',['../_sections_8php.html',1,'']]],
  ['sectionsnested_2ephp_7246',['SectionsNested.php',['../_sections_nested_8php.html',1,'']]],
  ['security_2emd_7247',['SECURITY.md',['../_s_e_c_u_r_i_t_y_8md.html',1,'']]],
  ['see_2ephp_7248',['See.php',['../_see_8php.html',1,'']]],
  ['selector_2ephp_7249',['Selector.php',['../_selector_8php.html',1,'']]],
  ['self_5f_2ephp_7250',['Self_.php',['../_self___8php.html',1,'']]],
  ['selfdescribing_2ephp_7251',['SelfDescribing.php',['../_self_describing_8php.html',1,'']]],
  ['serializer_2ephp_7252',['Serializer.php',['../_serializer_8php.html',1,'']]],
  ['setnullfilter_2ephp_7253',['SetNullFilter.php',['../_set_null_filter_8php.html',1,'']]],
  ['shadows_2emd_7254',['shadows.md',['../shadows_8md.html',1,'']]],
  ['shallowcopyfilter_2ephp_7255',['ShallowCopyFilter.php',['../_shallow_copy_filter_8php.html',1,'']]],
  ['shellexec_2ephp_7256',['ShellExec.php',['../_shell_exec_8php.html',1,'']]],
  ['shiftleft_2ephp_7257',['ShiftLeft.php',['../_binary_op_2_shift_left_8php.html',1,'(Global Namespace)'],['../_assign_op_2_shift_left_8php.html',1,'(Global Namespace)']]],
  ['shiftright_2ephp_7258',['ShiftRight.php',['../_binary_op_2_shift_right_8php.html',1,'(Global Namespace)'],['../_assign_op_2_shift_right_8php.html',1,'(Global Namespace)']]],
  ['simple_2ephp_7259',['Simple.php',['../_simple_8php.html',1,'']]],
  ['simpletype_2ephp_7260',['SimpleType.php',['../_simple_type_8php.html',1,'']]],
  ['since_2ephp_7261',['Since.php',['../_since_8php.html',1,'']]],
  ['sizing_2emd_7262',['sizing.md',['../sizing_8md.html',1,'']]],
  ['skippedtest_2ephp_7263',['SkippedTest.php',['../_skipped_test_8php.html',1,'']]],
  ['skippedtestcase_2ephp_7264',['SkippedTestCase.php',['../_skipped_test_case_8php.html',1,'']]],
  ['skippedtesterror_2ephp_7265',['SkippedTestError.php',['../_skipped_test_error_8php.html',1,'']]],
  ['skippedtestsuiteerror_2ephp_7266',['SkippedTestSuiteError.php',['../_skipped_test_suite_error_8php.html',1,'']]],
  ['smaller_2ephp_7267',['Smaller.php',['../_smaller_8php.html',1,'']]],
  ['smallerorequal_2ephp_7268',['SmallerOrEqual.php',['../_smaller_or_equal_8php.html',1,'']]],
  ['snapshot_2ephp_7269',['Snapshot.php',['../_snapshot_8php.html',1,'']]],
  ['snapshotnodelist_2ephp_7270',['SnapshotNodeList.php',['../_snapshot_node_list_8php.html',1,'']]],
  ['soapextensionnotavailableexception_2ephp_7271',['SoapExtensionNotAvailableException.php',['../_soap_extension_not_available_exception_8php.html',1,'']]],
  ['source_2ephp_7272',['Source.php',['../mustache_2mustache_2src_2_mustache_2_source_8php.html',1,'(Global Namespace)'],['../phpunit_2php-code-coverage_2src_2_report_2_xml_2_source_8php.html',1,'(Global Namespace)'],['../phpdocumentor_2reflection-docblock_2src_2_doc_block_2_tags_2_source_8php.html',1,'(Global Namespace)']]],
  ['spaceship_2ephp_7273',['Spaceship.php',['../_spaceship_8php.html',1,'']]],
  ['spacing_2emd_7274',['spacing.md',['../spacing_8md.html',1,'']]],
  ['specificmajorandminorversionconstraint_2ephp_7275',['SpecificMajorAndMinorVersionConstraint.php',['../_specific_major_and_minor_version_constraint_8php.html',1,'']]],
  ['specificmajorversionconstraint_2ephp_7276',['SpecificMajorVersionConstraint.php',['../_specific_major_version_constraint_8php.html',1,'']]],
  ['spectestcase_2ephp_7277',['SpecTestCase.php',['../_spec_test_case_8php.html',1,'']]],
  ['spinners_2emd_7278',['spinners.md',['../spinners_8md.html',1,'']]],
  ['spldoublylinkedlist_2ephp_7279',['SplDoublyLinkedList.php',['../_spl_doubly_linked_list_8php.html',1,'']]],
  ['spldoublylinkedlistfilter_2ephp_7280',['SplDoublyLinkedListFilter.php',['../_spl_doubly_linked_list_filter_8php.html',1,'']]],
  ['splfileinfopatch_2ephp_7281',['SplFileInfoPatch.php',['../_spl_file_info_patch_8php.html',1,'']]],
  ['splobjectstoragecomparator_2ephp_7282',['SplObjectStorageComparator.php',['../_spl_object_storage_comparator_8php.html',1,'']]],
  ['standard_2ephp_7283',['Standard.php',['../_standard_8php.html',1,'']]],
  ['standardtagfactory_2ephp_7284',['StandardTagFactory.php',['../_standard_tag_factory_8php.html',1,'']]],
  ['standardtestsuiteloader_2ephp_7285',['StandardTestSuiteLoader.php',['../_standard_test_suite_loader_8php.html',1,'']]],
  ['static_5f_2ephp_7286',['Static_.php',['../nikic_2php-parser_2lib_2_php_parser_2_node_2_stmt_2_static___8php.html',1,'(Global Namespace)'],['../phpdocumentor_2type-resolver_2src_2_types_2_static___8php.html',1,'(Global Namespace)']]],
  ['staticanalysiscachenotconfiguredexception_2ephp_7287',['StaticAnalysisCacheNotConfiguredException.php',['../_static_analysis_cache_not_configured_exception_8php.html',1,'']]],
  ['staticcall_2ephp_7288',['StaticCall.php',['../_static_call_8php.html',1,'']]],
  ['staticmethod_2ephp_7289',['StaticMethod.php',['../_static_method_8php.html',1,'']]],
  ['staticpropertyfetch_2ephp_7290',['StaticPropertyFetch.php',['../_static_property_fetch_8php.html',1,'']]],
  ['statictype_2ephp_7291',['StaticType.php',['../_static_type_8php.html',1,'']]],
  ['staticvar_2ephp_7292',['StaticVar.php',['../_static_var_8php.html',1,'']]],
  ['stmt_2ephp_7293',['Stmt.php',['../_stmt_8php.html',1,'']]],
  ['streamlogger_2ephp_7294',['StreamLogger.php',['../_stream_logger_8php.html',1,'']]],
  ['streamloggertest_2ephp_7295',['StreamLoggerTest.php',['../_stream_logger_test_8php.html',1,'']]],
  ['stretched_2dlink_2emd_7296',['stretched-link.md',['../stretched-link_8md.html',1,'']]],
  ['strictcallablestest_2ephp_7297',['StrictCallablesTest.php',['../_strict_callables_test_8php.html',1,'']]],
  ['strictunifieddiffoutputbuilder_2ephp_7298',['StrictUnifiedDiffOutputBuilder.php',['../_strict_unified_diff_output_builder_8php.html',1,'']]],
  ['string_5f_2ephp_7299',['String_.php',['../nikic_2php-parser_2lib_2_php_parser_2_node_2_expr_2_cast_2_string___8php.html',1,'(Global Namespace)'],['../nikic_2php-parser_2lib_2_php_parser_2_node_2_scalar_2_string___8php.html',1,'(Global Namespace)'],['../phpdocumentor_2type-resolver_2src_2_types_2_string___8php.html',1,'(Global Namespace)']]],
  ['stringcontains_2ephp_7300',['StringContains.php',['../_string_contains_8php.html',1,'']]],
  ['stringcontainstoken_2ephp_7301',['StringContainsToken.php',['../_string_contains_token_8php.html',1,'']]],
  ['stringendswith_2ephp_7302',['StringEndsWith.php',['../_string_ends_with_8php.html',1,'']]],
  ['stringloader_2ephp_7303',['StringLoader.php',['../_string_loader_8php.html',1,'']]],
  ['stringloadertest_2ephp_7304',['StringLoaderTest.php',['../_string_loader_test_8php.html',1,'']]],
  ['stringmatchesformatdescription_2ephp_7305',['StringMatchesFormatDescription.php',['../_string_matches_format_description_8php.html',1,'']]],
  ['stringstartswith_2ephp_7306',['StringStartsWith.php',['../_string_starts_with_8php.html',1,'']]],
  ['stringutil_2ephp_7307',['StringUtil.php',['../_string_util_8php.html',1,'']]],
  ['stub_2ephp_7308',['Stub.php',['../_stub_8php.html',1,'(Global Namespace)'],['../_stub_2_stub_8php.html',1,'(Global Namespace)'],['../_builder_2_stub_8php.html',1,'(Global Namespace)']]],
  ['successfulschemadetectionresult_2ephp_7309',['SuccessfulSchemaDetectionResult.php',['../_successful_schema_detection_result_8php.html',1,'']]],
  ['switch_5f_2ephp_7310',['Switch_.php',['../_switch___8php.html',1,'']]],
  ['syntaxexception_2ephp_7311',['SyntaxException.php',['../_syntax_exception_8php.html',1,'']]],
  ['syntaxexceptiontest_2ephp_7312',['SyntaxExceptionTest.php',['../_syntax_exception_test_8php.html',1,'']]],
  ['syntheticerror_2ephp_7313',['SyntheticError.php',['../_synthetic_error_8php.html',1,'']]],
  ['syntheticskippederror_2ephp_7314',['SyntheticSkippedError.php',['../_synthetic_skipped_error_8php.html',1,'']]]
];
