var class_sebastian_bergmann_1_1_code_coverage_1_1_no_code_coverage_driver_with_path_coverage_support_available_exception =
[
    [ "__construct", "class_sebastian_bergmann_1_1_code_coverage_1_1_no_code_coverage_driver_with_path_coverage_support_available_exception.html#a60d4a5fd965a215cc3dd159e83678bb8", null ]
];